<?php
// Generated by ZF2's ./bin/classmap_generator.php
return array(
    'W91\Module'                                    => __DIR__ . '/Module.php',
    'W91\Auth\Http'                                 => __DIR__ . '/src/W91/Auth/Http.php', 
    'W91\Auth\HttpInterface'                        => __DIR__ . '/src/W91/Auth/HttpInterface.php',
    'W91\Controller\IndexController'                => __DIR__ . '/src/W91/Controller/IndexController.php',
    'W91\Controller\UserController'                 => __DIR__ . '/src/W91/Controller/UserController.php', 
    'W91\Controller\PayController'                  => __DIR__ . '/src/W91/Controller/PayController.php', 
    'W91\Exception\InvalidArgumentException'        => __DIR__ . '/src/W91/Exception/InvalidArgumentException.php', 
    'W91\Listener\AuthLoggerListener'               => __DIR__ . '/src/W91/Listener/AuthLoggerListener.php',
    'W91\Sdk\Sdk'                                   => __DIR__ . '/src/W91/Sdk/Sdk.php', 
    'W91\Service\AuthHttpFactory'                   => __DIR__ . '/src/W91/Service/AuthHttpFactory.php',
    'W91Test\Framework\TestCase'                    => __DIR__ . '/tests/W91/Framework/TestCase.php',
    'W91Test\SampleTest'                            => __DIR__ . '/tests/W91/SampleTest.php',
);
