<?php
/**
 * 第三方登陆验证
 * 
 * @category MobilePf2
 * @package QihuTest
 * @namespace QihuTest
 * @copyright Copyright (c) 2004 - $Year$ Zfirm Inc.
 * @author $Author: zhangweiwen $
 * @version $Id$
 */

/**
 * This file defines configuration for running this module's unit tests.
 * Modules are usually located inside a ZF2 application, so a sane default
 * for ZEND_FRAMEWORK_PATH is the vendor folder in the application.
 *
 * If testing outside of a ZF2 application, do not edit this file. Instead,
 * create a TestConfiguration.php file that will be used in it's place.
 * TestConfiguration.php is ignored by git so that environment specific
 * configuration is not committed.
 *
 * Never commit plaintext passwords to the source code repository.
 */

define('APPLICATION_PATH', realpath(__DIR__ . '/../../../'));
define('ZF2_PATH', realpath(APPLICATION_PATH . '/vendor/zendframework/zendframework/library/'));

/**
 * The bootstrap supports several more options, however most modules will
 * not need to define these.
 */

// Override the module name (usually because the namespace is something besides the root foldername)
// define('MODULE_NAME', 'SomeModuleName');

// Add additional paths where additional modules can be found
// $additionalModulePaths = array(
//     '/usr/share/lib/php/',
//     'SomeVendor' => realpath('/path/for/some/vendor/library'),
// );
$additionalNamespaces = array(
	'Platform' => realpath(APPLICATION_PATH . '/module/Platform/src/Platform'), 
    'Zfirm' => realpath(APPLICATION_PATH . '/module/Zfirm/src/Zfirm'), 
    'org\bovigo\vfs' => realpath(APPLICATION_PATH . '/vendor/mikey179/vfsStream/src/main/php/org/bovigo/vfs'), 
);

// Add dependencies, for example a vendor may create several modules that all depend on a common library
// $moduleDependencies = array('SomeVendor');
