<?php
// Generated by ZF2's ./bin/classmap_generator.php
return array(
    'Qihu\Module'                               => __DIR__ . '/Module.php',
    'Qihu\Auth\Http'                            => __DIR__ . '/src/Qihu/Auth/Http.php', 
    'Qihu\Auth\HttpInterface'                   => __DIR__ . '/src/Qihu/Auth/HttpInterface.php', 
    'Qihu\Controller\IndexController'           => __DIR__ . '/src/Qihu/Controller/IndexController.php',
    'Qihu\Controller\UserController'            => __DIR__ . '/src/Qihu/Controller/UserController.php',
    'Qihu\Controller\PayController'             => __DIR__ . '/src/Qihu/Controller/PayController.php',
    'Qihu\Exception\InvalidArgumentException'   => __DIR__ . '/src/Qihu/Exception/InvalidArgumentException.php',  
    'Qihu\Listener\AuthLoggerListener'          => __DIR__ . '/src/Qihu/Listener/AuthLoggerListener.php', 
    'Qihu\Sdk\QClient'                          => __DIR__ . '/src/Qihu/Sdk/QClient.php', 
    'Qihu\Sdk\QHelper'                          => __DIR__ . '/src/Qihu/Sdk/QHelper.php', 
    'Qihu\Sdk\QHttp'                            => __DIR__ . '/src/Qihu/Sdk/QHttp.php', 
    'Qihu\Sdk\QOAuth2'                          => __DIR__ . '/src/Qihu/Sdk/QOAuth2.php', 
    'Qihu\Service\AuthHttpFactory'              => __DIR__ . '/src/Qihu/Service/AuthHttpFactory.php', 
    'QihuTest\Framework\TestCase'               => __DIR__ . '/tests/Qihu/Framework/TestCase.php',
    'QihuTest\SampleTest'                       => __DIR__ . '/tests/Qihu/SampleTest.php',
    'QihuTest\Auth\HttpTest'                    => __DIR__ . '/tests/Qihu/Auth/HttpTest.php', 
    'QihuTest\Controller\UserControllerTest'    => __DIR__ . '/tests/Qihu/Controller/UserControllerTest.php', 
    'QihuTest\Listener\AuthLoggerListenerTest'  => __DIR__ . '/tests/Qihu/Listener/AuthLoggerListenerTest.php', 
    'QihuTest\Service\AuthHttpFactoryTest'      => __DIR__ . '/tests/Qihu/Service/AuthHttpFactoryTest.php', 
);
