<?php
// Generated by ZF2's ./bin/classmap_generator.php
return array(
    'Platform\Module'                                   => __DIR__ . '/Module.php',
    'Platform\Auth\Event'                               => __DIR__ . '/src/Platform/Auth/Event.php', 
    'Platform\Auth\HttpAbstract'                        => __DIR__ . '/src/Platform/Auth/HttpAbstract.php', 
    'Platform\Auth\HttpInterface'                       => __DIR__ . '/src/Platform/Auth/HttpInterface.php', 
    'Platform\Log\AuthLoggerListenerAbstract'           => __DIR__ . '/src/Platform/Log/AuthLoggerListenerAbstract.php', 
    'Platform\Log\LoggerAbstractServiceFactory'         => __DIR__ . '/src/Platform/Log/LoggerAbstractServiceFactory.php',
    'Platform\Log\PayLoggerListenerAbstract'            => __DIR__ . '/src/Platform/Log/PayLoggerListenerAbstract.php',  
    'Platform\Pay\HttpInterface'                        => __DIR__ . '/src/Platform/Pay/HttpInterface.php', 
    'Platform\Pay\Event'                                => __DIR__ . '/src/Platform/Pay/Event.php', 
    'Platform\Response\Success'                         => __DIR__ . '/src/Platform/Response/Success.php', 
    'Platform\Response\Failure'                         => __DIR__ . '/src/Platform/Response/Failure.php',
    'PlatformTest\Auth\HttpAbstractTest'                => __DIR__ . '/tests/Platform/Auth/HttpAbstractTest.php', 
    'PlatformTest\Log\AuthLoggerListenerAbstractTest'   => __DIR__ . '/tests/Platform/Log/AuthLoggerListenerAbstractTest.php', 
    'PlatformTest\Log\LoggerAbstractServiceFactoryTest' => __DIR__ . '/tests/Platform/Log/LoggerAbstractServiceFactoryTest.php',  
);
